create database product;
use product;
create table warhous(party_code int primary key,party_name varchar(30),customer_item varchar(30), item_name varchar(30),currency_code varchar(30),quantity int,grossweight int,volume int,total_value int,total_pieces int);
select * from warhous;
insert into warhous values(1,"A","steel","steel rods","USD",250,5000,12.5,12500,250),(2,"B","plastic","plastic containers","USD",1200,600,18,4800,1200),(3,"C","Wood","wooden pallets","USD",150,2250,33,3750,150),(4,"D","Card","Cardboard boxes","USD",3000,450,22,6000,3000),(5,"E","copper","copper wires","USD",500,1500,4,15000,500),(6,"F","AL","Aluminium sheets","USD",320,3200,9.6,9600,320),(7,"G","Glass","Glass pannel","USD",200,2400,11,8000,200),(8,"H","Motor","Motor engines","USD",50,7500,10,25000,50),(9,"I","Tire","Tires","USD",800,4000,16,12000,800),(10,"J","LED","LED Lights","USD",2000,300,3.5,5000,2000);
select * from warhous;
select party_code from warhous;
select SUM(quantity) from warhous;
select SUM(total_pieces) from warhous;
select SUM(grossweight) from warhous;
select SUM(volume) from warhous;
select SUM(total_value) from warhous;
select total_pieces from warhous group by party_code,party_name,customer_item,item_name,currency_code having SUM(total_pieces) >0 order by party_code;
select AVG(grossweight) from warhous;
select AVG(total_pieces) from warhous;
select round(AVG(total_pieces),3) from warhous;
select round(SUM(volume),2) from warhous;
select customer_item from warhous where customer_item regexp 's$';
select customer_item from warhous where customer_item regexp '[db]';
select party_code,AVG(grossweight) from warhous group by party_code;
select party_code,round(AVG(grossweight),2) from warhous group by party_code;
select party_name,SUM(Volume) from warhous group by party_name;
select party_code,SUM(quantity),round(AVG(total_value),2) from warhous group by party_code;
select curdate(),date_sub(curdate(),interval 50 day);
select curdate(),date_add(curdate(),interval 100 day); 
select SUM(quantity) As total_quantity from warhous;
Select item_name,total_value from warhous where total_value > 10000;
Select SUM(total_value) As warehouse_stock_value from warhous;
select item_name,total_value from warhous order by total_value DESC LIMIT 3;
Select Customer_item,SUM(quantity) as total_qty,SUM(total_value) As total_val from warhous group by customer_item;
select currency_code,SUM(total_value) As total_val from warhous group by currency_code;
select party_name,COUNT(*) as item_count from warhous group by party_name order by item_count DESC;
select * from warhous where item_name LIKE "%copper%";
select item_name,total_value,RANK() over(order by total_value DESC) As value_rank from warhous;

